/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import Negocio.ProcesosJuego;
import Objetos.ObjJugador;
import Objetos.ObjNumpartido;
import Objetos.ObjPartidareal;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static principal.FrmPerfiles.*;

/**
 *
 * @author Lukestas
 */
public class FrmJuego extends javax.swing.JDialog {

    JButton[] lista = new JButton[16];
    JButton[] lista2 = new JButton[3];
    String[] lista3 = new String[0];
    String test;
    String nombre;
    String sigana = "FALSO";
    String puntos1 = "0";
    String puntos2 = "0";
    int numfichas2 = 0;
    int posicion = 0;
    String FechaHora;
    String numpartidox="";
    String numpartidox2="";
    

    ProcesosJuego process = new ProcesosJuego();

    /**
     * Creates new form FrmJuego
     */
    public FrmJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Deteccion();
        //numpartido();
        txtNombreJugador1.setText(txtNombre1.getText());
        txtNombreJugador2.setText(txtNombre2.getText());
        txtJugador.setText(txtNombreJugador1.getText() + "oooo");
        setLocationRelativeTo(null);
        ObtenerFechaHora();
        ArrayList<ObjJugador> jug = ObjJugador.listaUsuarios;
        for (int i = 0; i < jug.size(); i++) {
            System.out.println(jug.get(i).getNombre2());
            System.out.println(jug.get(i).getNombre1());
        }
    }

    public void ObtenerFechaHora() {
        DateTimeFormatter hora = DateTimeFormatter.ofPattern("dd-MM-yyyy hh:mm");
        FechaHora = hora.format(LocalDateTime.now());
    }

    public void Deteccion() {
        A1.addActionListener(new PiezaPulsada(A1));
        A2.addActionListener(new PiezaPulsada(A2));
        A3.addActionListener(new PiezaPulsada(A3));
        A4.addActionListener(new PiezaPulsada(A4));
        A5.addActionListener(new PiezaPulsada(A5));
        A6.addActionListener(new PiezaPulsada(A6));
        A7.addActionListener(new PiezaPulsada(A7));
        A8.addActionListener(new PiezaPulsada(A8));

        R1.addActionListener(new PiezaPulsada(R1));
        R2.addActionListener(new PiezaPulsada(R2));
        R3.addActionListener(new PiezaPulsada(R3));
        R4.addActionListener(new PiezaPulsada(R4));
        R5.addActionListener(new PiezaPulsada(R5));
        R6.addActionListener(new PiezaPulsada(R6));
        R7.addActionListener(new PiezaPulsada(R7));
        R8.addActionListener(new PiezaPulsada(R8));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        R1 = new javax.swing.JButton();
        R2 = new javax.swing.JButton();
        R3 = new javax.swing.JButton();
        R4 = new javax.swing.JButton();
        R5 = new javax.swing.JButton();
        R6 = new javax.swing.JButton();
        R7 = new javax.swing.JButton();
        R8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Seleccionado = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtJugador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreJugador1 = new javax.swing.JLabel();
        txtNombreJugador2 = new javax.swing.JLabel();
        txtPuntosJugador1 = new javax.swing.JLabel();
        txtPuntosJugador2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumPartida = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Posicion1 = new javax.swing.JButton();
        Posicion2 = new javax.swing.JButton();
        Posicion3 = new javax.swing.JButton();
        Posicion4 = new javax.swing.JButton();
        Posicion5 = new javax.swing.JButton();
        Posicion6 = new javax.swing.JButton();
        Posicion7 = new javax.swing.JButton();
        Posicion8 = new javax.swing.JButton();
        Posicion9 = new javax.swing.JButton();
        Posicion10 = new javax.swing.JButton();
        Posicion11 = new javax.swing.JButton();
        Posicion12 = new javax.swing.JButton();
        Posicion13 = new javax.swing.JButton();
        Posicion14 = new javax.swing.JButton();
        Posicion15 = new javax.swing.JButton();
        Posicion16 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        numpartida = new javax.swing.JLabel();
        asd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Fichas");

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulChiquitoCirculoHueco.png"))); // NOI18N

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulChiquitoCirculoCompleto.png"))); // NOI18N

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulChiquitoCuadradoHueco.png"))); // NOI18N

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulChiquitoCuadradoCompleto.png"))); // NOI18N

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulGrandeCirculoHueco.png"))); // NOI18N

        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulGrandeCirculoCompleto.png"))); // NOI18N

        A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulGrandeCuadradoCompleto.png"))); // NOI18N

        R1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaChiquitoCirculoHueco.png"))); // NOI18N

        R2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaChiquitoCirculoCompleto.png"))); // NOI18N

        R3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaChiquitoCuadradoHueco.png"))); // NOI18N

        R4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaChiquitoCuadradoCompleto.png"))); // NOI18N
        R4.setToolTipText("");

        R5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaGrandeCirculoHueco.png"))); // NOI18N

        R6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaGrandeCirculoCompleto.png"))); // NOI18N

        R7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaGrandeCuadradoHueco.png"))); // NOI18N

        R8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RosaGrandeCuadradoCompleto.png"))); // NOI18N

        jLabel2.setText("Seleccionada:");

        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AzulGrandeCuadradoHueco.png"))); // NOI18N

        jLabel4.setText("Turno de:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(53, 53, 53)
                                .addComponent(txtJugador))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Seleccionado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJugador))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Gané");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Presione si considera haber ganado");

        jLabel5.setText("Jugador 1:");

        jLabel6.setText("Jugador 2:");

        txtPuntosJugador1.setText("0");

        txtPuntosJugador2.setText("0");

        jLabel11.setText("pts");

        jLabel12.setText("pts");

        jLabel7.setText("Partida:");

        txtNumPartida.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Posicion5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Posicion9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Posicion13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Posicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Posicion4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Posicion11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Posicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Posicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Posicion3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Posicion4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Posicion5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Posicion6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Posicion7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Posicion8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Posicion9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Posicion10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Posicion12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Posicion13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Posicion14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Posicion15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Posicion16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("1");

        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("2");

        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("3");

        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("4");

        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("1");

        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("2");

        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("3");

        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("4");

        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("B");

        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("A");

        numpartida.setText("jLabel20");

        asd.setText("Numero de partida:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumPartida))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNombreJugador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuntosJugador1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNombreJugador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuntosJugador2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(asd)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(numpartida)
                                .addGap(56, 56, 56))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumPartida))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNombreJugador1)
                            .addComponent(txtPuntosJugador1)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNombreJugador2)
                            .addComponent(txtPuntosJugador2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(asd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numpartida)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Agregacion() {
        lista[0] = Posicion1;
        lista[1] = Posicion2;
        lista[2] = Posicion3;
        lista[3] = Posicion4;
        lista[4] = Posicion5;
        lista[5] = Posicion6;
        lista[6] = Posicion7;
        lista[7] = Posicion8;
        lista[8] = Posicion9;
        lista[9] = Posicion10;
        lista[10] = Posicion11;
        lista[11] = Posicion12;
        lista[12] = Posicion13;
        lista[13] = Posicion14;
        lista[14] = Posicion15;
        lista[15] = Posicion16;
    }
    
    public void numpartido(){
        
        ArrayList<ObjNumpartido> numpartido = process.LeerUsuarios2();
        
       for (int i = 0; i < numpartido.size(); i++) {
           numpartidox= numpartido.get(0).getNumpartido();
           numpartidox2=String.valueOf(Integer.valueOf(numpartidox+1));
           
       }
        ObjNumpartido.numpartido2.add(new ObjNumpartido(numpartidox2));
       ArrayList<ObjNumpartido> test = ObjNumpartido.numpartido2;
       process.InsertarNumero(test);
        System.out.println(numpartidox2);
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Agregacion();

        JButton[] verificables = new JButton[4];
        for (int i = 0; i < lista.length; i++) {
            if (lista[i].getIcon() != null) {
                if ((i == 0) || (i == 4) || (i == 8) || (i == 12)) {
                    //if ((i == 0) || (i == 3) || (i == 7) || (i == 11)) {
                    if (lista[i + 1].getIcon() != null) {
                        if (lista[i + 2].getIcon() != null) {
                            if (lista[i + 3].getIcon() != null) {
                                verificables[0] = lista[i];
                                verificables[1] = lista[i + 1];
                                verificables[2] = lista[i + 2];
                                verificables[3] = lista[i + 3];
                                System.out.println(verificables[0].getIcon().toString());
                                System.out.println(verificables[1].getIcon().toString());
                                System.out.println(verificables[2].getIcon().toString());
                                System.out.println(verificables[3].getIcon().toString());
                                sigana = process.resultado(verificables);
                                if (!sigana.equals("FALSO")) {
                                    String fila = process.posicionfila(i);
                                    JOptionPane.showMessageDialog(null, "Felicidades " + nombre + " has ganado\nFichas: " + sigana + ", " + fila, "Ganaste!", JOptionPane.ERROR_MESSAGE);

                                    //validar quien gana los puntos
                                    puntosganados();
                                    ganado();
                                    break;
                                }

                            }
                        }
                    }
                }
            }
        }
        //columnas
        for (int i = 0; i < lista.length; i++) {
            if (!sigana.equals("FALSO")) {
                break;
            }
            if (lista[i].getIcon() != null) {
                if ((i == 0) || (i == 1) || (i == 2) || (i == 3)) {
                    if (lista[i + 4].getIcon() != null) {
                        if (lista[i + 8].getIcon() != null) {
                            if (lista[i + 12].getIcon() != null) {
                                verificables[0] = lista[i];
                                verificables[1] = lista[i + 4];
                                verificables[2] = lista[i + 8];
                                verificables[3] = lista[i + 12];
                                System.out.println(verificables[0].getIcon().toString());
                                System.out.println(verificables[1].getIcon().toString());
                                System.out.println(verificables[2].getIcon().toString());
                                System.out.println(verificables[3].getIcon().toString());
                                System.out.println("verticales");
                                sigana = process.resultado(verificables);
                                if (!sigana.equals("FALSO")) {
                                    i++;
                                    JOptionPane.showMessageDialog(null, " Felicidades " + nombre + " has ganado\nFichas: " + sigana + ", Columna " + i, "Ganaste!", JOptionPane.ERROR_MESSAGE);
                                    //validar quien gana los puntos
                                   puntosganados();
                                   ganado();
                                    break;
                                }

                            }
                        }
                    }
                }
            }
        }
        for (int i = 0; i < lista.length; i++) {
            if (!sigana.equals("FALSO")) {
                break;
            }
            if (lista[i].getIcon() != null) {
                if ((i == 0)) {
                    if (lista[5].getIcon() != null) {
                        if (lista[10].getIcon() != null) {
                            if (lista[15].getIcon() != null) {
                                verificables[0] = lista[0];
                                verificables[1] = lista[5];
                                verificables[2] = lista[10];
                                verificables[3] = lista[15];
                                System.out.println(verificables[0].getIcon().toString());
                                System.out.println(verificables[1].getIcon().toString());
                                System.out.println(verificables[2].getIcon().toString());
                                System.out.println(verificables[3].getIcon().toString());
                                System.out.println("diagonal A");
                                sigana = process.resultado(verificables);
                                if (!sigana.equals("FALSO")) {
                                    JOptionPane.showMessageDialog(null, "Felicidades " + nombre + " has ganado\nFichas: " + sigana + ", Diagonal A", "Ganaste!", JOptionPane.ERROR_MESSAGE);
                                    //validar quien gana los puntos
                                   puntosganados();
                                   ganado();
                                    break;
                                }

                            }
                        }
                    }
                }
            }
        }
        for (int i = 0; i < lista.length; i++) {
            if (!sigana.equals("FALSO")) {
                break;
            }
            if (lista[i].getIcon() != null) {
                if ((i == 3)) {
                    if (lista[6].getIcon() != null) {
                        if (lista[9].getIcon() != null) {
                            if (lista[12].getIcon() != null) {
                                verificables[0] = lista[3];
                                verificables[1] = lista[6];
                                verificables[2] = lista[9];
                                verificables[3] = lista[12];
                                System.out.println(verificables[0].getIcon().toString());
                                System.out.println(verificables[1].getIcon().toString());
                                System.out.println(verificables[2].getIcon().toString());
                                System.out.println(verificables[3].getIcon().toString());
                                System.out.println("diagonal B");
                                sigana = process.resultado(verificables);
                                if (!sigana.equals("FALSO")) {
                                    JOptionPane.showMessageDialog(null, "Felicidades " + nombre + " has ganado\nFichas: " + sigana + ", Diagonal B", "Ganaste!", JOptionPane.ERROR_MESSAGE);
                                    //validar quien gana los puntos
                                    puntosganados();
                                    ganado();
                                    break;
                                }

                            }
                        }
                    }
                }
            }
            
        }
        
        if (sigana.equals("FALSO")) {
            JOptionPane.showMessageDialog(null, "No has ganado, acabas de perder 2 pts", "Oh!Oh!", JOptionPane.ERROR_MESSAGE);
        } else {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea jugar de nuevo?");
            if (opcion == 0) {
                this.dispose();
                FrmPerfiles ventanaPerfiles = new FrmPerfiles(null, true);
                ventanaPerfiles.pack();
                ventanaPerfiles.setVisible(true);
            } else if (opcion == 1) {
                this.dispose();
                System.exit(0);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private class PiezaPulsada implements ActionListener {

        private JButton boton;

        public PiezaPulsada(JButton boton) {
            this.boton = boton;

        }

        @Override
        public void actionPerformed(ActionEvent e) {
            
            numfichas2 = numfichas2 + 1;
            if (Seleccionado.getIcon() != null) {
                JOptionPane.showMessageDialog(null, "La pieza ya fue seleccionada", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                Seleccionado.setIcon(boton.getIcon());
                verificado();
                boton.setEnabled(false);
            }

        }

    

        public void verificado() {
            Posicion1.addActionListener(new PuestosLibres(Posicion1));
            Posicion2.addActionListener(new PuestosLibres(Posicion2));
            Posicion3.addActionListener(new PuestosLibres(Posicion3));
            Posicion4.addActionListener(new PuestosLibres(Posicion4));
            Posicion5.addActionListener(new PuestosLibres(Posicion5));
            Posicion6.addActionListener(new PuestosLibres(Posicion6));
            Posicion7.addActionListener(new PuestosLibres(Posicion7));
            Posicion8.addActionListener(new PuestosLibres(Posicion8));
            Posicion9.addActionListener(new PuestosLibres(Posicion9));
            Posicion10.addActionListener(new PuestosLibres(Posicion10));
            Posicion11.addActionListener(new PuestosLibres(Posicion11));
            Posicion12.addActionListener(new PuestosLibres(Posicion12));
            Posicion13.addActionListener(new PuestosLibres(Posicion13));
            Posicion14.addActionListener(new PuestosLibres(Posicion14));
            Posicion15.addActionListener(new PuestosLibres(Posicion15));
            Posicion16.addActionListener(new PuestosLibres(Posicion16));
        }

        //  System.out.println(boton);
        //if(Seleccionado!=null){
        // JOptionPane.showMessageDialog(null, "Movimiento incorrecto");
        // }
        private class PuestosLibres implements ActionListener {

            private JButton libertad;

            public PuestosLibres(JButton libertad) {
                this.libertad = libertad;
            }

            @Override
            public void actionPerformed(ActionEvent e) {

                if (libertad.getIcon() == null) {
                    libertad.setIcon(Seleccionado.getIcon());
                    Seleccionado.setIcon(null);
                    if (posicion == 0) {
                        posicion = 1;
                        nombre = process.posicion(posicion);
                        txtJugador.setText(nombre);
                    } else {
                        posicion = 0;
                        nombre = process.posicion(posicion);
                        txtJugador.setText(nombre);
                    }

                }

            }

        }

    }

    public void ganado() {
        /*
               String numpartida;
    String nombre11;
    String nombre22;
    String puntos11;
    String puntos22;
    String numfichas;
    String tiempojuego;
         */

        String nombre1 = txtNombre1.getText();
        String nombre2 = txtNombre2.getText();
        String numfichas = String.valueOf(numfichas2);
        String tiempojuego = "0";

       
        ObjPartidareal.Partida.add(new ObjPartidareal("0",nombre1, nombre2, puntos1,puntos2,numfichas,tiempojuego));
        
        
        //testeando
        ArrayList<ObjPartidareal> test = ObjPartidareal.Partida;
        for (int i = 0; i < test.size(); i++) {
            System.out.println(test.get(i).getNombre11());
            System.out.println(test.get(i).getNombre22());
             System.out.println(test.get(i).getPuntos11());
             System.out.println(test.get(i).getPuntos22());
             System.out.println(test.get(i).getNumfichas());
             System.out.println(test.get(i).getTiempojuego());
        }

        process.InsertarUsuariocompra(test);
    }
    
        public void puntosganados() {
            //validar quien gana los puntos
            ArrayList<ObjJugador> asd = ObjJugador.listaUsuarios;
            for (int ix = 0; ix < asd.size(); ix++) {
                if (asd.get(0).getNombre1().equals(nombre)) {
                    puntos1 = "3";
                } else {
                    puntos2 = "3";
                }
            }
            System.out.println(puntos1+"/"+puntos2);
        }
        
        
     
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmJuego dialog = new FrmJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton Posicion1;
    private javax.swing.JButton Posicion10;
    private javax.swing.JButton Posicion11;
    private javax.swing.JButton Posicion12;
    private javax.swing.JButton Posicion13;
    private javax.swing.JButton Posicion14;
    private javax.swing.JButton Posicion15;
    private javax.swing.JButton Posicion16;
    private javax.swing.JButton Posicion2;
    private javax.swing.JButton Posicion3;
    private javax.swing.JButton Posicion4;
    private javax.swing.JButton Posicion5;
    private javax.swing.JButton Posicion6;
    private javax.swing.JButton Posicion7;
    private javax.swing.JButton Posicion8;
    private javax.swing.JButton Posicion9;
    private javax.swing.JButton R1;
    private javax.swing.JButton R2;
    private javax.swing.JButton R3;
    private javax.swing.JButton R4;
    private javax.swing.JButton R5;
    private javax.swing.JButton R6;
    private javax.swing.JButton R7;
    private javax.swing.JButton R8;
    private javax.swing.JButton Seleccionado;
    private javax.swing.JLabel asd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel numpartida;
    private javax.swing.JLabel txtJugador;
    private javax.swing.JLabel txtNombreJugador1;
    private javax.swing.JLabel txtNombreJugador2;
    private javax.swing.JLabel txtNumPartida;
    private javax.swing.JLabel txtPuntosJugador1;
    private javax.swing.JLabel txtPuntosJugador2;
    // End of variables declaration//GEN-END:variables
}
